"""baseline

Revision ID: 50984e4fef6b
Revises: 
Create Date: 2026-07-07 15:51:19.386505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50984e4fef6b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hr_admin_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('hashed_password', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hr_admin_users_username'), 'hr_admin_users', ['username'], unique=True)
    op.create_table('hr_assistant_audit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slack_user_id', sa.String(length=20), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('tables_accessed', sa.String(length=500), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('schema_rag_ms', sa.Integer(), nullable=True),
    sa.Column('agent_ms', sa.Integer(), nullable=True),
    sa.Column('total_ms', sa.Integer(), nullable=True),
    sa.Column('user_lookup_ms', sa.Integer(), nullable=True),
    sa.Column('rate_check_ms', sa.Integer(), nullable=True),
    sa.Column('history_fetch_ms', sa.Integer(), nullable=True),
    sa.Column('slack_post_ms', sa.Integer(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hr_assistant_audit_slack_user_id'), 'hr_assistant_audit', ['slack_user_id'], unique=False)
    op.create_table('hr_assistant_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('slack_user_id', sa.String(length=20), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slack_user_id', name='uq_hr_user_slack')
    )
    op.create_index(op.f('ix_hr_assistant_users_employee_id'), 'hr_assistant_users', ['employee_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hr_assistant_users_employee_id'), table_name='hr_assistant_users')
    op.drop_table('hr_assistant_users')
    op.drop_index(op.f('ix_hr_assistant_audit_slack_user_id'), table_name='hr_assistant_audit')
    op.drop_table('hr_assistant_audit')
    op.drop_index(op.f('ix_hr_admin_users_username'), table_name='hr_admin_users')
    op.drop_table('hr_admin_users')
    # ### end Alembic commands ###
